language: cpp

matrix:
  include:
    - compiler: gcc
    - compiler: clang

python:
  - "2.7"
  - "3.6"

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq default-jre
  - if [[ $TRAVIS_PYTHON_VERSION < 3; then pip install --user subprocess32 ]]
  - pip install --user subprocess32
  - make download

before_script:
  - make init

script:
  - make bin/sbu
  - make test
