language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq default-jre
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda info -a
  - conda create -q -n py2 python=2.7

before_script:
  - make init
  - python set_paths.py
  - pip install --user -e .
  - source activate py2
  - pip install --user -e .
  - source deactivate py2

script:
  #py3 test
  - make test

  #py2 test
  - source activate py2
  - make test
  - source deactivate py2
